### ISSUE TITLE
Parameters File

### ISSUE THREAD

**Issue by fabi92** [sfalkner/pySMAC#11]
paramstrings*.txt
1: cat_A='con', cat_B='plant', int_A='1', int_B='17', obj='A', ord_A='cold', ord_B='low'

This is the first utilized parameter set from the following parameters definition
    parameter_definition=dict(\
        int_A = ("integer", [1, 3],  1),
        cat_A = ("categorical", ["con","te","nance"], "con"),
        ord_A = ("ordinal", ["cold", "hot"], "cold"),
        int_B = ("integer", [17, 20], 17),
        cat_B = ("categorical", ["plant", "human", "animal"], "plant"),  
        ord_B = ("ordinal", ["low", "high"], "low"),
        obj =  ("categorical", ["A", "B"], "A")
        )

```
applied conditionals
    int_A    | obj in {A}
   cat_A    | obj in {A}
   ord_A    | obj in {A}
   int_B    | obj in {B}
   cat_B    | obj in {B}
   ord_B    | obj in {B}
```

During the runs the excluded parameters, according to the conditionals, are set to None. 
       active class:   A:
           int_A:  1, cat_A:  con, ord_A:  cold
           int_B:  None, cat_B:  None, ord_B:  None

However, in the paramstrings file the None values are replaced by random possible values from the input dictionary (see line 2). This is confusing and makes later evaluations more difficult. For example if you want to figure out how pysmac tries to optimize the parameters, by taking a look at the execution order.

**Comment by sfalkner** [comment]
While I agree that this is indeed confusing, it is a consequence of the internals of SMAC itself.

If you look harder at the paramstring file, you will notice that the variables that were set to None during the execution take their default value (not anything random). The reason is that all parameters have a value, and are assumed to take the specified default when inactive. 

With that, don't think pySMAC should interfere with the SMAC files itself, sorry. What you can do, if you really want to look into your runs, you could store the parameters and the return value for every call to your function yourself in a format you like (e.g., writing them into a file).  Please note that the paramstring file is no particular ordered to reflect the best found configuration so far. It is merely for bookkeeping and reconstructing the SMAC run afterwards.
